name: Deploy to Production

on:
  push:
    branches: [main]
  workflow_dispatch: # Permite ejecución manual

jobs:
  deploy:
    name: Deploy to Railway
    runs-on: ubuntu-latest
    environment: 
      name: production
      url: https://your-app-name.up.railway.app
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Run quality checks
        run: npm run quality

      - name: Build application
        run: npm run build:prod

      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          npm install -g @railway/cli
          railway up --detach

      - name: Post-deploy health check
        run: |
          echo "✅ Deployment completed successfully"
          echo "🚀 Bot should be running on Railway"
          # Aquí podrías agregar un health check real si tienes un endpoint HTTP

  notify:
    name: Notify Deployment
    runs-on: ubuntu-latest
    needs: deploy
    if: always() # Se ejecuta incluso si deploy falla
    
    steps:
      - name: Notify success
        if: needs.deploy.result == 'success'
        run: |
          echo "🎉 Deployment successful!"
          echo "Bot version: ${{ github.sha }}"
          echo "Deployed at: $(date)"

      - name: Notify failure
        if: needs.deploy.result == 'failure'
        run: |
          echo "❌ Deployment failed!"
          echo "Check the logs for more details"
          exit 1